php console.php release yiiext/components/shoppingCart 0.6
php console.php release yiiext/behaviors/model/status 0.5
php console.php release yiiext/behaviors/model/taggable 1.0.1
php console.php release yiiext/behaviors/model/ensureNull 1.0.1
php console.php release yiiext/components/zendAutoloader 1.0
php console.php release yiiext/filters/setReturnUrl 1.0.1
php console.php release yiiext/renderers/dwoo 0.9.1
php console.php release yiiext/renderers/quicky 0.9.1
php console.php release yiiext/renderers/smarty 0.9.6
php console.php release yiiext/renderers/twig 0.9.2
php console.php release yiiext/widgets/uplodify 1.3
php console.php release yiiext/zii/widgets/grid/imageColumn 1.0
